server:
  port: 8083
spring:
  application:
    name: micro-weather-data
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 10
      password:
      poolMaxTotal: 1000
      poolMaxIdle: 500
      poolMaxWait: 500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
