server:
  port: 8084
spring:
  application:
    name: micro-weather-zuul
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    collector:
      rabbitmq:
        host: 
        port: 
        username: 
        password: 
        virtual-host: 
        queue: 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    data:
      path: /data/**
      serviceId: micro-weather-data
    city:
      path: /city/**
      serviceId: micro-weather-city

