server:
  port: 8081
spring:
  application:
    name: micro-weather-collection
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    collector:
      rabbitmq:
        host: 
        port: 
        username: 
        password: 
        virtual-host: 
        queue: 
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10
    password:
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMaxWait: 500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

