server:
  port: 8082
spring:
  application:
    name: micro-weather-city
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    collector:
      rabbitmq:
        host: 
        port: 5672
        username: 
        password: 
        virtual-host: 
        queue: 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
