server:
  port: 8085
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  application:
    name: micro-weather-report
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feignName:
        connnectTimeout: 50000
        readTimeout: 50000
  hystrix:
    enabled: true
    command:
      default:
        circuitBreaker:
          requestVolumeThreshold: 1000
        fallback:
          isolation:
            semaphore:
              maxConcurrentRequests: 10000
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 60000
    threadpool:
      default:
        coreSize: 10

  # 配置httpClient线程池
  httpclient:
    enabled: false
  okhttp:
    enabled: true






