server:
  port: 8085
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  application:
    name: micro-weather-report
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feignName:
        connnectTimeout: 50000
        readTimeout: 50000
  hystrix:
    enabled: true




